services:
  # Django
  - type: web
    name: shinkansen-simulator
    env: python
    region: Oregon, USA
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
    autoDeploy: true
